---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insolar-jepsen-deployment
spec:
  selector:
    matchLabels:
      app: insolar-jepsen
  replicas: 1
  template:
    metadata:
      labels:
        app: insolar-jepsen
    spec:
      containers:
      - name: insolar-pulsar
        image: insolar-jepsen
        imagePullPolicy: Never
        securityContext:
          privileged: true
        args:
        - /sbin/my_init
        volumeMounts:
        - name: config
          mountPath: /configs/
      volumes:
      - name: config
        configMap:
          name: pulsar-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: insolar-jepsen
  name: pulsar-config
data:
  pulsar.yml: |
      host:
        transport:
          protocol: TCP
          address: 127.0.0.1:0
          behindnat: false
        isrelay: false
        infinitybootstrap: false
        mintimeout: 1
        maxtimeout: 60
        timeoutmult: 2
        signmessages: false
        handshakesessionttl: 5000
      service:
        skip: 10
      ledger:
        storage:
          datadirectory: ./data
          txretriesonconflict: 3
        pulsemanager:
          heavysyncenabled: true
          heavysyncmessagelimit: 1048576
          heavybackoff:
            factor: 2
            jitter: true
            min: 200ms
            max: 2s
          splitthreshold: 1000
        recentstorage:
          defaultttl: 10
        lightchainlimit: 5
        jetsizeshistorydepth: 10
        exporter:
          exportlag: 40
      log:
        level: Debug
        adapter: logrus
        formatter: text
      metrics:
        listenaddress: 0.0.0.0:9090
        namespace: insolar
        zpagesenabled: true
        reportingperiod: 0s
      logicrunner:
        rpclisten: 127.0.0.1:7778
        rpcprotocol: tcp
        builtin: {}
        goplugin:
          runnerlisten: 127.0.0.1:7777
          runnerprotocol: tcp
      apirunner:
        address: localhost:19101
        call: /api/call
        rpc: /api/rpc
        timeout: 15
      pulsar:
        connectiontype: tcp
        mainlisteneraddress: 127.0.0.1:58090
        storage:
          datadirectory: ./data_pulsar
          txretriesonconflict: 0
        pulsetime: 10000
        receivingsigntimeout: 1000
        receivingnumbertimeout: 1000
        receivingvectortimeout: 1000
        receivingsignsforchosentimeout: 0
        neighbours: []
        numberdelta: 10
        distributiontransport:
          protocol: TCP
          address: 127.0.0.1:58091
          behindnat: false
        pulsedistributor:
          bootstraphosts:
          - 127.0.0.1:13831
          - 127.0.0.1:23832
          - 127.0.0.1:33833
          - 127.0.0.1:43834
          - 127.0.0.1:53835
          pingrequesttimeout: 1000
          randomhostsrequesttimeout: 1000
          pulserequesttimeout: 1000
          randomnodescount: 5
      versionmanager:
        minalowedversion: v0.3.0
      keyspath: scripts/insolard/configs/bootstrap_keys.json
      certificatepath: ""
      tracer:
        jaeger:
          collectorendpoint: ""
          agentendpoint: 127.0.0.1:6831
          probabilityrate: 1
        samplingrules: {}

---
